# Generated by Django 2.0.6 on 2018-07-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_userprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
