# Generated by Django 2.0.6 on 2018-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20180725_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='date_added',
            field=models.DateTimeField(verbose_name='Date Added'),
        ),
    ]
