# Generated by Django 2.0.7 on 2018-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20180727_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
