# Generated by Django 2.0.7 on 2018-08-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
