# Generated by Django 2.0.7 on 2018-08-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20180808_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/placeholder-profile-pic.png', upload_to='media/'),
        ),
    ]
