# Generated by Django 2.0.7 on 2018-08-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20180808_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='static/food/media/'),
        ),
    ]
